spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mariadb://localhost:3306/laptopshop
spring.datasource.username=root
spring.datasource.password=sapassword
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# spring.jpa.show-sql=true

#----------Cấu hình Security mặc định or Không cấu hinh-----------#
# #config spring security
# spring.security.user.name=admin
# spring.security.user.password=admin
